<?php

namespace AppBundle\Repository;

/**
 * CommandItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandItemRepository extends \Doctrine\ORM\EntityRepository
{
}
