<?php

namespace AppBundle\Repository;

/**
 * DoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineRepository extends \Doctrine\ORM\EntityRepository
{
}
