<?php

namespace AppBundle\Repository;

/**
 * FitCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
