<?php

namespace AppBundle\Repository;

/**
 * FitDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitDataRepository extends \Doctrine\ORM\EntityRepository
{
}
