<?php

namespace AppBundle\Repository;

/**
 * FitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitRepository extends \Doctrine\ORM\EntityRepository
{
}
