<?php

namespace AppBundle\Repository;

/**
 * FitSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
