<?php

namespace AppBundle\Repository;

/**
 * FleetMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FleetMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
