<?php

namespace AppBundle\Repository;

/**
 * RecruitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitementRepository extends \Doctrine\ORM\EntityRepository
{
}
