<?php

namespace AppBundle\Repository;

/**
 * SkillLevelItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillLevelItemRepository extends \Doctrine\ORM\EntityRepository
{
}
