<?php

namespace AppBundle\Repository;

/**
 * SkillSetDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillSetDataRepository extends \Doctrine\ORM\EntityRepository
{
}
