<?php

namespace AppBundle\Repository;

/**
 * SkillSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillSetRepository extends \Doctrine\ORM\EntityRepository
{
}
