# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        our_users:
            entity: { class: AppBundle\Entity\User, property: name }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            logout:
                path: /logout
                target: /


            form_login:
                login_path:  /login

            access_denied_handler: access_denied.handler

            logout_on_user_change: true


    access_control:
        # allow anonymous access to the homepage:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_APPLY:       ROLE_GUEST
        ROLE_MEMBER:      ROLE_GUEST
        ROLE_PROD:        ROLE_MEMBER
        ROLE_FIT:         ROLE_MEMBER
        ROLE_ADMIN:       [ROLE_MEMBER, ROLE_MODERATOR, ROLE_FIT, ROLE_PROD]